package frames;

public class frmHomepage extends javax.swing.JFrame {

    /**
     * Creates new form frmHomepage
     */
    public frmHomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnCreateUser = new javax.swing.JButton();
        btnAccessMessage = new javax.swing.JButton();
        btnLeaveMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to MessageBox!");
        setAutoRequestFocus(false);

        pnlWelcome.setBackground(new java.awt.Color(255, 204, 255));

        lblWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lblWelcome.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 0, 0));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to MessageBox!");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        pnlWelcomeLayout.setVerticalGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(pnlWelcomeLayout.createSequentialGroup().addContainerGap().addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pnlButtons.setBackground(new java.awt.Color(255, 204, 255));

        btnCreateUser.setBackground(new java.awt.Color(255, 204, 0));
        btnCreateUser.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btnCreateUser.setText("Create user");
        btnCreateUser.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCreateUser.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCreateUser.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnAccessMessage.setBackground(new java.awt.Color(0, 204, 51));
        btnAccessMessage.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btnAccessMessage.setText("Access message");
        btnAccessMessage.setMaximumSize(new java.awt.Dimension(150, 50));
        btnAccessMessage.setMinimumSize(new java.awt.Dimension(150, 50));
        btnAccessMessage.setPreferredSize(new java.awt.Dimension(150, 50));
        btnAccessMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessMessageActionPerformed(evt);
            }
        });

        btnLeaveMessage.setBackground(new java.awt.Color(0, 204, 204));
        btnLeaveMessage.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        btnLeaveMessage.setText("Leave a message");
        btnLeaveMessage.setMaximumSize(new java.awt.Dimension(150, 50));
        btnLeaveMessage.setMinimumSize(new java.awt.Dimension(150, 50));
        btnLeaveMessage.setPreferredSize(new java.awt.Dimension(150, 50));
        btnLeaveMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup().addGap(60, 60, 60).addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(btnLeaveMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(btnAccessMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addGap(60, 60, 60)));
        pnlButtonsLayout.setVerticalGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(pnlButtonsLayout.createSequentialGroup().addGap(25, 25, 25).addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(25, 25, 25).addComponent(btnAccessMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE).addComponent(btnLeaveMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(25, 25, 25)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap(130, Short.MAX_VALUE).addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 130, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap(20, Short.MAX_VALUE).addComponent(pnlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(35, 35, 35).addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(25, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessMessageActionPerformed
        frmAccesspage frmAccesspage = new frmAccesspage();
        frmAccesspage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccessMessageActionPerformed

    private void btnLeaveMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveMessageActionPerformed
        frmMessageRegisterpage frmRegisterpage = new frmMessageRegisterpage();
        frmRegisterpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLeaveMessageActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        frmUserRegisterpage frmUserRegisterpage = new frmUserRegisterpage();
        frmUserRegisterpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessMessage;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnLeaveMessage;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlWelcome;
    // End of variables declaration//GEN-END:variables
}
