/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import entities.User;
import utils.FileReadHelper;
import utils.FileWriteHelper;
import utils.HashHelper;

import javax.swing.*;
import java.io.IOException;
import java.util.ArrayList;

public class frmUserRegisterpage extends javax.swing.JFrame {
    ArrayList<User> userList;
    String[] usernamesArray;
    String userDataFilePath = "users.data";

    /**
     * Creates new form frmUserRegisterpage
     */
    public frmUserRegisterpage() {
        initComponents();
        userList = FileReadHelper.createUserList(userDataFilePath);
        usernamesArray = FileReadHelper.createUsernamesArray(userList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserRegister = new javax.swing.JLabel();
        lblUserPsw = new javax.swing.JLabel();
        txtFieldUsername = new javax.swing.JTextField();
        lblUserPswConfirm = new javax.swing.JLabel();
        passwordUserpswd = new javax.swing.JPasswordField();
        cboxShowUserPassword = new javax.swing.JCheckBox();
        btnHome = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        passwordUserpswd1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER REGISTER");

        lblUserRegister.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        lblUserRegister.setText("User Register");

        lblUserPsw.setText("User Password");

        lblUserPswConfirm.setText("Confirm Password");

        cboxShowUserPassword.setText("Show User Password");
        cboxShowUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxShowUserPasswordActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 204, 204));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 51, 0));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSignup.setBackground(new java.awt.Color(102, 204, 0));
        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        lblUsername.setText("Username*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addGap(10, 10, 10)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUserPswConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserPsw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(cboxShowUserPassword))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordUserpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordUserpswd1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblUserRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblUserRegister)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPsw)
                    .addComponent(passwordUserpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPswConfirm)
                    .addComponent(passwordUserpswd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(cboxShowUserPassword)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSignup)
                    .addComponent(btnHome))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetFields() {
        txtFieldUsername.setText("");
        passwordUserpswd.setText("");
        passwordUserpswd1.setText("");
    }

    private void cboxShowUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxShowUserPasswordActionPerformed
        if (cboxShowUserPassword.isSelected()) {
            passwordUserpswd.setEchoChar((char) 0);
            passwordUserpswd1.setEchoChar((char) 0); //password = JPasswordField
        } else {
            passwordUserpswd.setEchoChar('*');
            passwordUserpswd1.setEchoChar('*');
        }
    }//GEN-LAST:event_cboxShowUserPasswordActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String username = txtFieldUsername.getText();
        String rawPassword = String.valueOf(passwordUserpswd.getPassword());
        String rawPasswordConfirmation = String.valueOf(passwordUserpswd1.getPassword());

        if (username.equals("") || rawPassword.equals("") || rawPasswordConfirmation.equals("")) {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty!", "USER REGISTER ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            if (rawPassword.equals(rawPasswordConfirmation)) {
                if (FileReadHelper.usernameUniquenessCheck(username, usernamesArray)) {

                    String hashedPassword = HashHelper.getMd5(rawPassword);
                    String outputUserInfo = username + "\t" + hashedPassword;
                    try {
                        FileWriteHelper.writeNewLine(userDataFilePath, outputUserInfo);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                    userList.add(new User(username, hashedPassword));
                    usernamesArray = FileReadHelper.createUsernamesArray(userList);
                    JOptionPane.showMessageDialog(null, "New user has been registered!", "USER ADDED", JOptionPane.INFORMATION_MESSAGE);
                    resetFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Username must be unique! Please try another username.", "USERNAME UNIQUENESS ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Passwords are not equal! Please enter the same password values.", "PASSWORD ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        passwordUserpswd.setText("");
        passwordUserpswd1.setText("");
        txtFieldUsername.setText("");
        cboxShowUserPassword.setSelected(false);
        passwordUserpswd.setEchoChar('*');
        passwordUserpswd1.setEchoChar('*');
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        frmHomepage frmHomepage = new frmHomepage();
        frmHomepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUserRegisterpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUserRegisterpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUserRegisterpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUserRegisterpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUserRegisterpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignup;
    private javax.swing.JCheckBox cboxShowUserPassword;
    private javax.swing.JLabel lblUserPsw;
    private javax.swing.JLabel lblUserPswConfirm;
    private javax.swing.JLabel lblUserRegister;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField passwordUserpswd;
    private javax.swing.JPasswordField passwordUserpswd1;
    private javax.swing.JTextField txtFieldUsername;
    // End of variables declaration//GEN-END:variables
}
